name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ strategy.matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm test
      - name: Run feature tests
        run: |
          npm test:feature
        env:
          CI: true
